repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    - id: black
      language_version: python3
      args: ["--line-length=120"]

-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2  # Use the latest from https://github.com/timothycrosley/isort/tags
    hooks:
    - id: isort
      args: ["--profile", "black"]

-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1  # Use the latest nbQA version
    hooks:
      - id: nbqa-black
        args: ['--line-length=120']
        additional_dependencies: [black==23.12.1]
      - id: nbqa-isort
        additional_dependencies: [isort==5.13.2]

-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0  # Use the latest from https://github.com/pycqa/flake8/tags
    hooks:
    - id: flake8

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0  # Use the latest from https://github.com/pre-commit/mirrors-mypy/tags
    hooks:
    - id: mypy
      additional_dependencies: ['types-PyYAML']

